name: Build .dylib with Theos

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    name: Build with Theos
    runs-on: macos-latest

    steps:
      - name: Tải mã nguồn
        uses: actions/checkout@v4

      # Cài Theos
      - name: Cài Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      # Kiểm tra file
      - name: Kiểm tra
        run: |
          ls -la
          echo "THEOS=$THEOS"

      # Build
      - name: Build
        run: |
          export THEOS=$HOME/theos
          make clean
          make THEOS=$THEOS

      # Tải kết quả
      - name: Upload .dylib
        uses: actions/upload-artifact@v4
        with:
          name: libmodmenu.dylib
          path: |
            ./*.dylib
            ./obj/*.dylib
          retention-days: 14
